name: SteveSkyLobby
version: '1.0-SNAPSHOT'
main: com.steve.steveSkyLobby.SteveSkyLobby
api-version: '1.21'
commands:
  biomeset:
    description: Set biomes.
    usage: "Usage: biomeset [large]"
  showbiome:
    description: Visualize block biomes
    usage: "Usage: showbiomes [large]"
  makeWorldCopy:
    description: Make a new world copying the voidBuildingWorld
    usage: "Usage: makeWorldCopy"
  sendPlayer:
    description: Send player to a world
    usage: "Usage: sendPlayer"